import type { RepositoryAnalysis } from '@phoenix/legacy-analysis';
import type { SourceLocation, SqlStatement } from '@phoenix/shared';
import type { CustomCheck } from '@phoenix/agent-runtime';

/**
 * The orientation digest handed to the Archaeologist.
 *
 * Static analysis output is far too large to put in a prompt, and most of it is noise for the
 * question "what does this system mean?". The digest keeps the parts that carry semantic weight —
 * routes, database-side behaviour, migrations, schedules, configuration, drifted duplicates,
 * suspicious constructs, flows — one entry per line, bounded, with an explicit note whenever a
 * section was cut. A digest that silently dropped entries would be a lie of omission, so the counts
 * are always shown next to the excerpt.
 *
 * The digest quotes no source text. It carries names, kinds, locations, counts and analyzer prose;
 * verbatim bytes live in `sourceLocation.snippet` inside the persisted artifact. A digest that
 * embedded the code would let a model answer without opening a file, and the read-before-you-cite
 * gate would reject every citation it then produced — the agent would be unable to satisfy its own
 * evidence requirement no matter how hard it tried.
 */

export interface DigestOptions {
  maxChars?: number;
  maxEntriesPerSection?: number;
}

const DEFAULT_MAX_CHARS = 60_000;
const DEFAULT_MAX_ENTRIES = 40;
const STATEMENTS_SHOWN = 6;

export function discoveryDigest(analysis: RepositoryAnalysis, options: DigestOptions = {}): string {
  const maxChars = options.maxChars ?? DEFAULT_MAX_CHARS;
  const maxEntries = options.maxEntriesPerSection ?? DEFAULT_MAX_ENTRIES;
  const lines: string[] = [];
  let overflowed = false;

  const push = (line: string): void => {
    if (overflowed) return;
    if (lines.join('\n').length + line.length + 1 > maxChars) {
      overflowed = true;
      lines.push('', `… digest truncated at ${maxChars} characters; sections below this line are missing …`);
      return;
    }
    lines.push(line);
  };

  /** Emits at most `maxEntries` rendered entries and reports how many were held back. */
  const list = <T>(items: readonly T[], render: (item: T) => string): void => {
    for (const item of items.slice(0, maxEntries)) push(render(item));
    if (items.length > maxEntries) push(`… ${items.length - maxEntries} more not shown …`);
  };

  const heading = (title: string, count?: number): void => {
    push('');
    push(count === undefined ? `## ${title}` : `## ${title} (${count})`);
  };

  const map = analysis.repositoryMap;
  const location = (where: SourceLocation | undefined): string =>
    where === undefined ? '(no location)' : `${where.path}${where.startLine !== undefined ? `:${where.startLine}` : ''}`;

  push(`# Discovery digest for ${map.rootPath}`);
  push(`Generated by ${map.generator} at ${map.generatedAt}`);
  push(
    `${map.fileCount} files, ${map.totalBytes} bytes, primary language ${map.primaryLanguage ?? 'unknown'}` +
      (analysis.truncated ? ' — INVENTORY TRUNCATED, the file list is incomplete' : ''),
  );
  push(
    'This digest quotes no source code. Every line is an index entry: read the file it points at with read_file before you assert anything about it.',
  );

  heading('Languages', map.languages.length);
  list(map.languages, (language) =>
    `- ${language.name}: ${language.fileCount} files, ${language.bytes} bytes` +
      (language.declaredLevel !== undefined ? `, declared level ${language.declaredLevel}` : '') +
      (language.extensions.length > 0 ? ` (${language.extensions.join(', ')})` : ''),
  );

  heading('Build systems', map.buildSystems.length);
  for (const build of map.buildSystems) {
    push(`- ${build.kind} @ ${build.manifestPath}`);
    const commands = Object.entries(build.commands)
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => `${key}: ${value}`);
    if (commands.length > 0) push(`  commands → ${commands.join(' | ')}`);
    if (build.dependencies.length > 0) {
      push(
        `  dependencies (${build.dependencies.length}) → ` +
          build.dependencies
            .slice(0, maxEntries)
            .map((dependency) => `${dependency.name}${dependency.version !== undefined ? `@${dependency.version}` : ''}`)
            .join(', ') +
          (build.dependencies.length > maxEntries ? `, … ${build.dependencies.length - maxEntries} more` : ''),
      );
    }
  }

  heading('Frameworks', map.frameworks.length);
  list(map.frameworks, (framework) =>
    `- ${framework.name}${framework.version !== undefined ? `@${framework.version}` : ''} — evidence: ${framework.evidence
      .map((item) => location(item.location))
      .join(', ')}`,
  );

  heading('Entry points', map.entryPoints.length);
  list(
    map.entryPoints,
    (entry) =>
      `- [${entry.kind}] ${entry.label} — ${location(entry.location)}${entry.notes !== undefined ? ` — ${entry.notes}` : ''}`,
  );

  heading('HTTP endpoints', map.httpEndpoints.length);
  list(
    map.httpEndpoints,
    (endpoint) =>
      `- ${endpoint.method} ${endpoint.path} → ${endpoint.handler.symbol ?? 'handler'} @ ${location(endpoint.handler)}` +
      (endpoint.anomalies.length > 0 ? ` — ANOMALIES: ${endpoint.anomalies.join('; ')}` : ''),
  );

  heading('Database objects', map.databaseObjects.length);
  list(map.databaseObjects, (object) => {
    const columns =
      object.columns.length > 0
        ? ` columns: ${object.columns
            .slice(0, 20)
            .map((column) => `${column.name} ${column.type}${column.nullable === false ? ' NOT NULL' : ''}`)
            .join(', ')}${object.columns.length > 20 ? `, … ${object.columns.length - 20} more` : ''}`
        : '';
    const definedIn = object.definedIn !== undefined ? ` — defined in ${location(object.definedIn)}` : '';
    const behavior =
      object.behavior === undefined
        ? ''
        : `\n  DATABASE-SIDE BEHAVIOR: ${object.behavior.length} characters of logic, body withheld — read ${location(object.definedIn)} to see it`;
    return `- ${object.kind} ${object.name}${definedIn}${columns}${behavior}`;
  });

  heading('Migrations', map.migrations.length);
  list(
    map.migrations,
    (migration) =>
      `- ${migration.version} (${migration.tool}) ${migration.path}` +
      (migration.appliesDatabaseBehavior ? ' — APPLIES DATABASE-SIDE BEHAVIOR' : '') +
      (migration.objectsTouched.length > 0 ? ` — touches ${migration.objectsTouched.join(', ')}` : '') +
      (migration.description !== undefined ? ` — ${migration.description}` : ''),
  );

  heading('Database access from code', map.databaseAccess.length);
  list(map.databaseAccess, (access) => {
    const shown = access.statements.slice(0, STATEMENTS_SHOWN).map((statement) => {
      const flags = sqlSignalNames(statement.signals);
      return `- ${statement.kind}${statement.writes ? ' (write)' : ''} @ ${location(statement.location)}${
        flags.length > 0 ? ` [${flags.join(', ')}]` : ''
      }`;
    });
    return (
      `- [${access.mechanism}] ${location(access.location)} tables: ${access.tables.join(', ') || '(none resolved)'}` +
      `\n  ${access.statements.length} statement(s) — SQL text withheld, read the locations below` +
      (shown.length > 0 ? `\n    ${shown.join('\n    ')}` : '') +
      (access.statements.length > STATEMENTS_SHOWN ? `\n    … ${access.statements.length - STATEMENTS_SHOWN} more statements …` : '')
    );
  });

  heading('Scheduled jobs', map.scheduledJobs.length);
  list(
    map.scheduledJobs,
    (job) =>
      `- ${job.label} — ${job.schedule} (${job.scheduleKind}) @ ${location(job.location)}; idempotent: ${
        job.idempotent === undefined ? `UNKNOWN (${job.idempotencyEpistemicStatus})` : String(job.idempotent)
      }${job.notes !== undefined ? ` — ${job.notes}` : ''}`,
  );

  heading('Configuration', map.configuration.length);
  list(map.configuration, (source) => {
    const keys = source.keys
      .slice(0, 30)
      .map((key) => (key.secret ? `${key.key}=<secret>` : key.key))
      .join(', ');
    return (
      `- ${source.path} (${source.format}) ${source.keys.length} key(s), values withheld — read the file to see them` +
      (keys.length > 0 ? `\n    ${keys}${source.keys.length > 30 ? `, … ${source.keys.length - 30} more keys` : ''}` : '') +
      (source.environmentOverrides.length > 0 ? `\n    env overrides: ${source.environmentOverrides.join(', ')}` : '')
    );
  });

  heading('External dependencies', map.externalDependencies.length);
  list(
    map.externalDependencies,
    (dependency) =>
      `- ${dependency.name} (${dependency.kind})${dependency.version !== undefined ? `@${dependency.version}` : ''}` +
        (dependency.nondeterministic ? ' — NONDETERMINISTIC' : '') +
        (dependency.usedBy.length > 0 ? ` — used by ${dependency.usedBy.slice(0, 5).map(location).join(', ')}` : ''),
  );

  heading('Duplicated logic', map.duplicationClusters.length);
  list(map.duplicationClusters, (cluster) => {
    const members = cluster.members.map((member) => `${member.symbol ?? member.path}${member.startLine !== undefined ? `:${member.startLine}` : ''}`);
    const drift = [...new Set(cluster.driftEvidence.map((item) => location(item.location)).filter((where) => where !== '(no location)'))];
    return (
      `- ${cluster.id}${cluster.drifted ? ' (DRIFTED — the copies disagree)' : ''}: ${clip(cluster.description, 400)}` +
      `\n  members: ${members.join(' | ')}` +
      (cluster.similarity !== undefined ? `\n  similarity: ${cluster.similarity.toFixed(2)}` : '') +
      (drift.length > 0 ? `\n  drift evidence at: ${drift.join(' | ')} — read both sides before saying which is right` : '')
    );
  });

  heading('Suspicious constructs', map.suspiciousBehaviors.length);
  list(
    map.suspiciousBehaviors,
    (behavior) =>
      `- [${behavior.category}] ${clip(behavior.description, 300)} @ ${location(behavior.location)} → ${behavior.recommendedAction}`,
  );

  heading('Call graph');
  const graph = analysis.dependencyMap;
  push(`- ${graph.nodes.length} nodes, ${graph.edges.length} edges`);
  push(`- edge kinds: ${countBy(graph.edges.map((edge) => edge.kind))}`);
  if (graph.hotspots.length > 0) {
    push(
      `- hotspots: ${graph.hotspots
        .slice(0, 12)
        .map((hotspot) => `${hotspot.id} (in ${hotspot.inbound}, out ${hotspot.outbound})`)
        .join(', ')}`,
    );
  }
  if (graph.cycles.length > 0) {
    push(`- cycles (${graph.cycles.length}): ${graph.cycles.slice(0, 6).map((cycle) => cycle.join(' → ')).join(' | ')}`);
  }

  heading('Data flows', analysis.dataFlow.flows.length);
  list(analysis.dataFlow.flows, (flow) => {
    const steps = flow.steps
      .slice(0, 8)
      .map((step) => `${step.component}: ${clip(step.action, 120)}` + (step.writes.length > 0 ? ` [writes ${step.writes.join(',')}]` : ''))
      .join('\n    ');
    return (
      `- ${flow.name} (trigger: ${clip(flow.trigger, 120)}) — stores: ${flow.dataStores.join(', ') || '(none resolved)'}` +
      `\n  ${flow.epistemicStatus} confidence ${flow.confidence.toFixed(2)}\n    ${steps}` +
      (flow.steps.length > 8 ? `\n    … ${flow.steps.length - 8} more steps …` : '') +
      (flow.notes !== undefined ? `\n  note: ${clip(flow.notes, 200)}` : '')
    );
  });

  if (map.ignoredPaths.length > 0) {
    heading('Ignored paths', map.ignoredPaths.length);
    list(map.ignoredPaths, (path) => `- ${path}`);
  }

  return lines.join('\n');
}

/**
 * Self-check on the deterministic layer. Phoenix rejects its own analysis when the graph refers to
 * nodes that do not exist, a flow claims a store nothing knows about, or a finding points at a file
 * that is not in the inventory. Without this, a bug in the analyzer would travel downstream as fact.
 */
export function discoveryConsistencyCheck(analysis: RepositoryAnalysis, maxProblems = 12): CustomCheck {
  return () => {
    const problems: string[] = [];
    const push = (problem: string): void => {
      if (problems.length < maxProblems) problems.push(problem);
    };

    const files = new Set(analysis.repositoryMap.files.map((file) => file.path));
    const nodeIds = new Set(analysis.dependencyMap.nodes.map((node) => node.id));
    for (const edge of analysis.dependencyMap.edges) {
      if (!nodeIds.has(edge.from)) push(`dependency edge ${edge.from} → ${edge.to} starts at an unknown node`);
      if (!nodeIds.has(edge.to)) push(`dependency edge ${edge.from} → ${edge.to} ends at an unknown node`);
    }

    const checkLocation = (where: SourceLocation | undefined, what: string): void => {
      if (where === undefined) return;
      if (!files.has(where.path)) push(`${what} cites ${where.path}, which is not in the file inventory`);
    };
    for (const endpoint of analysis.repositoryMap.httpEndpoints) checkLocation(endpoint.handler, `endpoint ${endpoint.method} ${endpoint.path}`);
    for (const entry of analysis.repositoryMap.entryPoints) checkLocation(entry.location, `entry point ${entry.label}`);
    for (const behavior of analysis.repositoryMap.suspiciousBehaviors) checkLocation(behavior.location, `suspicious construct ${behavior.id}`);

    const knownStores = new Set<string>();
    for (const object of analysis.repositoryMap.databaseObjects) {
      if (object.kind === 'table' || object.kind === 'view') knownStores.add(object.name);
    }
    for (const access of analysis.repositoryMap.databaseAccess) {
      for (const table of access.tables) knownStores.add(table);
    }
    for (const flow of analysis.dataFlow.flows) {
      for (const store of flow.dataStores) {
        if (!knownStores.has(store)) push(`flow ${flow.id} claims store "${store}", which no SQL or schema mentions`);
      }
      if (flow.steps.length === 0) push(`flow ${flow.id} has no steps`);
    }

    const counts = [
      `${analysis.repositoryMap.fileCount} files`,
      `${analysis.repositoryMap.httpEndpoints.length} endpoints`,
      `${analysis.dependencyMap.nodes.length} graph nodes`,
      `${analysis.dataFlow.flows.length} flows`,
      `${analysis.repositoryMap.suspiciousBehaviors.length} suspicious constructs`,
    ].join(', ');

    if (problems.length > 0) {
      return {
        satisfied: false,
        reason: `${problems.length} consistency problem(s) in the deterministic discovery output: ${problems.join('; ')}`,
        observed: counts,
      };
    }
    return { satisfied: true, observed: `discovery output is self-consistent (${counts})` };
  };
}

function countBy(values: readonly string[]): string {
  const counts = new Map<string, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([key, count]) => `${key} ${count}`)
    .join(', ');
}

/** Deterministic statement flags, as names. The statement text they were computed from is not index data. */
function sqlSignalNames(signals: SqlStatement['signals']): string[] {
  return [
    signals.hasRounding ? 'rounding' : '',
    signals.hasAggregate ? 'aggregate' : '',
    signals.hasOrderBy ? 'order-by' : '',
    signals.hasStringConcatenation ? 'string-concatenation' : '',
    signals.hasTransactionControl ? 'transaction-control' : '',
  ].filter((name) => name !== '');
}

function clip(text: string, max: number): string {
  const collapsed = text.replace(/\s+/g, ' ').trim();
  return collapsed.length <= max ? collapsed : `${collapsed.slice(0, Math.max(0, max - 1))}…`;
}

/** Kept exported for tests that assert the digest covers every analysis section. */
export function digestSectionTitles(digest: string): string[] {
  return digest
    .split('\n')
    .filter((line) => line.startsWith('## '))
    .map((line) => line.slice(3).replace(/ \(\d+\)$/, ''));
}
