import { z } from 'zod';
import {
  evidenceRefSchema,
  invariantIdSchema,
  isoTimestampSchema,
  ruleIdSchema,
  scenarioIdSchema,
  severitySchema,
} from './primitives.js';
import { agentRoleSchema } from './roles.js';
import { scenarioExecutionSchema } from './scenario.js';

/**
 * Differential testing contracts (brief §12).
 *
 * Normalization is explicit, justified and recorded. A normalized field always appears in the
 * report together with the reason and the rule that authorized it, so normalization can never
 * silently hide a meaningful difference.
 */

export const normalizationStrategySchema = z.enum([
  'ignore',
  'replace-constant',
  'timestamp-bucket',
  'uuid',
  'numeric-tolerance',
  'round-decimals',
  'regex-substitute',
  'sort-array',
]);
export type NormalizationStrategy = z.infer<typeof normalizationStrategySchema>;

export const normalizationRuleSchema = z
  .object({
    ruleId: z.string().min(1),
    /** Dotted path with `*` and `[*]` wildcards, e.g. `steps[*].responseBody.items[*].id`. */
    path: z.string().min(1),
    strategy: normalizationStrategySchema,
    value: z.unknown().optional(),
    tolerance: z.number().nonnegative().optional(),
    decimals: z.number().int().nonnegative().optional(),
    pattern: z.string().min(1).optional(),
    replacement: z.string().optional(),
    /** Mandatory justification: normalization without a reason is how differences get lost. */
    reason: z.string().min(10, 'normalization requires a justification of at least 10 characters'),
    requestedBy: agentRoleSchema,
    appliesTo: z.enum(['legacy', 'modern', 'both']).default('both'),
    scenarioIds: z.array(scenarioIdSchema).default([]),
    /** True when the field is generated by the system under test and carries no meaning. */
    fieldIsSystemGenerated: z.boolean().default(false),
  })
  .superRefine((rule, ctx) => {
    if (rule.strategy === 'numeric-tolerance' && rule.tolerance === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'numeric-tolerance requires `tolerance`' });
    }
    if (rule.strategy === 'round-decimals' && rule.decimals === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'round-decimals requires `decimals`' });
    }
    if (rule.strategy === 'regex-substitute' && rule.pattern === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'regex-substitute requires `pattern`' });
    }
    if (rule.strategy === 'replace-constant' && rule.value === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'replace-constant requires `value`' });
    }
  });
export type NormalizationRule = z.infer<typeof normalizationRuleSchema>;

export const normalizationConfigSchema = z.object({
  schemaVersion: z.literal(1).default(1),
  rules: z.array(normalizationRuleSchema).default([]),
  /**
   * When true, a scenario whose nondeterministic fields are not covered by an explicit rule is
   * reported as inconclusive instead of being compared with unreliable values.
   */
  failOnUnconfiguredNondeterminism: z.boolean().default(true),
});
export type NormalizationConfig = z.infer<typeof normalizationConfigSchema>;

export const normalizationAppliedSchema = z.object({
  ruleId: z.string().min(1),
  scenarioId: scenarioIdSchema,
  system: z.enum(['legacy', 'modern']),
  path: z.string().min(1),
  strategy: normalizationStrategySchema,
  before: z.unknown().optional(),
  after: z.unknown().optional(),
  reason: z.string().min(1),
});
export type NormalizationApplied = z.infer<typeof normalizationAppliedSchema>;

export const differenceKindSchema = z.enum([
  'missing-field',
  'extra-field',
  'value-difference',
  'type-difference',
  'http-status',
  'header-difference',
  'row-count',
  'row-content',
  'ordering',
  'precision',
  'error-vs-success',
  'side-effect',
  'state-divergence',
  'timing-threshold',
  'one-side-unreachable',
]);
export type DifferenceKind = z.infer<typeof differenceKindSchema>;

export const mismatchExplanationStatusSchema = z.enum([
  'unexplained',
  'explained-expected-divergence',
  'explained-normalization',
  'explained-legacy-defect-intentionally-preserved',
  'explained-legacy-defect-intentionally-fixed',
]);
export type MismatchExplanationStatus = z.infer<typeof mismatchExplanationStatusSchema>;

/** A single behavioral divergence between legacy and modern. Everything the brief requires. */
export const mismatchSchema = z.object({
  schemaVersion: z.literal(1).default(1),
  mismatchId: z.string().min(1),
  scenarioId: scenarioIdSchema,
  scenarioTitle: z.string().min(1).max(300),
  title: z.string().min(1).max(500),
  differenceKind: differenceKindSchema,
  /** Dotted path where the divergence was observed. */
  path: z.string().min(1),
  legacyValue: z.unknown().optional(),
  modernValue: z.unknown().optional(),
  severity: severitySchema,
  relevantRuleIds: z.array(ruleIdSchema).default([]),
  relevantInvariantIds: z.array(invariantIdSchema).default([]),
  evidence: z.array(evidenceRefSchema).min(1, 'a mismatch must carry evidence'),
  normalized: z.boolean().default(false),
  normalizationRuleIds: z.array(z.string().min(1)).default([]),
  explanationStatus: mismatchExplanationStatusSchema.default('unexplained'),
  explanation: z.string().max(4000).optional(),
  explainedBy: agentRoleSchema.optional(),
  reproducible: z.boolean().default(false),
  reproduction: z.string().max(8000).optional(),
  firstObservedAt: isoTimestampSchema,
  observedCount: z.number().int().positive().default(1),
  /** Set once a repair iteration has addressed this mismatch. */
  resolvedAt: isoTimestampSchema.optional(),
  resolvedByIteration: z.number().int().positive().optional(),
});
export type Mismatch = z.infer<typeof mismatchSchema>;

export const differentialComparisonSchema = z.object({
  scenarioId: scenarioIdSchema,
  scenarioTitle: z.string().min(1).max(300),
  category: z.string().min(1).max(64),
  legacy: scenarioExecutionSchema.optional(),
  modern: scenarioExecutionSchema.optional(),
  /** Values actually compared, after normalization. */
  normalizedLegacy: z.unknown().optional(),
  normalizedModern: z.unknown().optional(),
  equal: z.boolean(),
  outcome: z.enum(['equal', 'divergent', 'inconclusive', 'legacy-unreachable', 'modern-unreachable']),
  inconclusiveReason: z.string().max(2000).optional(),
  mismatches: z.array(z.string().min(1)).default([]),
  normalizationApplied: z.array(normalizationAppliedSchema).default([]),
  durationMs: z.number().int().nonnegative(),
});
export type DifferentialComparison = z.infer<typeof differentialComparisonSchema>;

export const differentialStatisticsSchema = z.object({
  scenarios: z.number().int().nonnegative(),
  equal: z.number().int().nonnegative(),
  divergent: z.number().int().nonnegative(),
  inconclusive: z.number().int().nonnegative(),
  unreachable: z.number().int().nonnegative(),
  mismatches: z.number().int().nonnegative(),
  unexplainedMismatches: z.number().int().nonnegative(),
  bySeverity: z.record(severitySchema, z.number().int().nonnegative()),
  normalizationApplications: z.number().int().nonnegative(),
});
export type DifferentialStatistics = z.infer<typeof differentialStatisticsSchema>;

export const differentialReportSchema = z.object({
  schemaVersion: z.literal(1).default(1),
  runId: z.string().min(1),
  generatedAt: isoTimestampSchema,
  generatedBy: agentRoleSchema,
  normalization: normalizationConfigSchema,
  comparisons: z.array(differentialComparisonSchema).default([]),
  mismatches: z.array(mismatchSchema).default([]),
  statistics: differentialStatisticsSchema,
  /** Human-readable summary; the machine-readable content above is authoritative. */
  summary: z.string().max(8000).optional(),
});
export type DifferentialReport = z.infer<typeof differentialReportSchema>;

export function emptyDifferentialStatistics(): DifferentialStatistics {
  return differentialStatisticsSchema.parse({
    scenarios: 0,
    equal: 0,
    divergent: 0,
    inconclusive: 0,
    unreachable: 0,
    mismatches: 0,
    unexplainedMismatches: 0,
    bySeverity: { CRITICAL: 0, MAJOR: 0, MINOR: 0, INFO: 0 },
    normalizationApplications: 0,
  });
}

export function computeDifferentialStatistics(
  report: Pick<DifferentialReport, 'comparisons' | 'mismatches'>,
): DifferentialStatistics {
  const bySeverity: Record<z.infer<typeof severitySchema>, number> = {
    CRITICAL: 0,
    MAJOR: 0,
    MINOR: 0,
    INFO: 0,
  };
  for (const mismatch of report.mismatches) bySeverity[mismatch.severity] += 1;
  return differentialStatisticsSchema.parse({
    scenarios: report.comparisons.length,
    equal: report.comparisons.filter((c) => c.outcome === 'equal').length,
    divergent: report.comparisons.filter((c) => c.outcome === 'divergent').length,
    inconclusive: report.comparisons.filter((c) => c.outcome === 'inconclusive').length,
    unreachable: report.comparisons.filter(
      (c) => c.outcome === 'legacy-unreachable' || c.outcome === 'modern-unreachable',
    ).length,
    mismatches: report.mismatches.length,
    unexplainedMismatches: report.mismatches.filter((m) => m.explanationStatus === 'unexplained')
      .length,
    bySeverity,
    normalizationApplications: report.comparisons.reduce(
      (acc, c) => acc + c.normalizationApplied.length,
      0,
    ),
  });
}
