import { describe, expect, it } from 'vitest';
import { hashStable } from '@phoenix/shared';
import {
  buildDifferentialReport,
  compareSuite,
  describeDifferentialReport,
  type CompareSuiteResult,
} from '../src/index.js';
import {
  LEGACY_FEE,
  assertion,
  caseItem,
  execution,
  feeCase,
  feeModern,
  outcome,
  suiteOf,
} from './support.js';

const RUN_ID = 'run_test-report';
const FIXED_NOW = new Date('2026-01-02T03:04:05.000Z');

function mixedResult(): CompareSuiteResult {
  const equal = feeCase({ caseId: 'CHR-FEE-001', legacyFee: LEGACY_FEE });
  const divergent = feeCase({ caseId: 'CHR-FEE-002', legacyFee: LEGACY_FEE });
  const skipped = feeCase({ caseId: 'CHR-FEE-003', legacyFee: LEGACY_FEE, status: 'inconclusive' });
  const suite = suiteOf({
    cases: [equal.item, divergent.item, skipped.item],
    captures: [equal.baseline, divergent.baseline, skipped.baseline],
  });
  return compareSuite({
    suite,
    modernExecutions: [
      { caseId: 'CHR-FEE-001', execution: feeModern(LEGACY_FEE) },
      { caseId: 'CHR-FEE-002', execution: feeModern(2) },
      { caseId: 'CHR-FEE-003', execution: feeModern(LEGACY_FEE) },
    ],
  });
}

describe('buildDifferentialReport', () => {
  it('aggregates comparison statistics and fills in the default normalization config', () => {
    const result = mixedResult();
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: result.comparisons,
      mismatches: result.mismatches,
      now: () => FIXED_NOW,
    });

    expect(report.runId).toBe(RUN_ID);
    expect(report.generatedAt).toBe('2026-01-02T03:04:05.000Z');
    expect(report.generatedBy).toBe('differential-verifier');
    expect(report.normalization).toEqual({
      schemaVersion: 1,
      rules: [],
      failOnUnconfiguredNondeterminism: true,
    });
    expect(report.summary).toBeUndefined();
    expect(report.statistics).toEqual({
      scenarios: 3,
      equal: 1,
      divergent: 1,
      inconclusive: 1,
      unreachable: 0,
      mismatches: 1,
      unexplainedMismatches: 1,
      bySeverity: { CRITICAL: 0, MAJOR: 1, MINOR: 0, INFO: 0 },
      normalizationApplications: 0,
    });
  });

  it('counts normalization applications recorded on equal comparisons', () => {
    const baseline = execution('legacy', [
      outcome('transfer', {
        httpStatus: 200,
        responseBody: { transferId: 'TR-1', fee: LEGACY_FEE },
      }),
    ]);
    const item = caseItem({
      caseId: 'CHR-NORM-001',
      status: 'passing-against-legacy',
      captureExecutionId: hashStable(baseline),
      assertions: [
        assertion({
          assertionId: 'CHR-NORM-001-A1',
          kind: 'json-value',
          path: 'responseBody.transferId',
          expected: 'TR-1',
          normalized: true,
          normalization: {
            reason: 'varied-across-repeated-legacy-executions',
            policy: 'ignore-transfer-id',
            observedValues: ['TR-1', 'TR-2'],
          },
        }),
      ],
    });
    const suite = suiteOf({ cases: [item], captures: [baseline] });
    const result = compareSuite({
      suite,
      modernExecutions: [
        {
          caseId: 'CHR-NORM-001',
          execution: execution('modern', [
            outcome('transfer', {
              httpStatus: 200,
              responseBody: { transferId: 'TR-9', fee: LEGACY_FEE },
            }),
          ]),
        },
      ],
    });
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: result.comparisons,
      mismatches: result.mismatches,
      now: () => FIXED_NOW,
    });

    expect(report.statistics.equal).toBe(1);
    expect(report.statistics.normalizationApplications).toBe(1);
    expect(describeDifferentialReport(report)).toContain(
      '1 normalization application(s) recorded',
    );
  });

  it('clips an oversized summary to the schema limit', () => {
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: [],
      mismatches: [],
      summary: 'x'.repeat(9_000),
      now: () => FIXED_NOW,
    });

    expect(report.summary).toHaveLength(8_000);
    expect(report.summary!.endsWith('…')).toBe(true);
  });

  it('honours an explicit normalization config and generator', () => {
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: [],
      mismatches: [],
      normalization: {
        schemaVersion: 1,
        rules: [
          {
            ruleId: 'ignore-transfer-id',
            path: 'responseBody.transferId',
            strategy: 'ignore',
            reason: 'transfer ids are regenerated by every system',
            requestedBy: 'differential-verifier',
            appliesTo: 'both',
            scenarioIds: [],
            fieldIsSystemGenerated: true,
          },
        ],
        failOnUnconfiguredNondeterminism: false,
      },
      generatedBy: 'differential-verifier',
      now: () => FIXED_NOW,
    });

    expect(report.normalization.failOnUnconfiguredNondeterminism).toBe(false);
    expect(report.normalization.rules).toHaveLength(1);
    expect(report.statistics.scenarios).toBe(0);
  });
});

describe('describeDifferentialReport', () => {
  it('headlines the equivalence ratio and renders the mismatch with both values', () => {
    const result = mixedResult();
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: result.comparisons,
      mismatches: result.mismatches,
      now: () => FIXED_NOW,
    });
    const text = describeDifferentialReport(report);

    expect(text.split('\n')[0]).toBe('1/3 scenarios equivalent, 1 mismatch');
    expect(text).toContain('MISMATCH:');
    expect(text).toContain('legacy 2.01 vs modern 2');
    expect(text).toContain('scn_chr-fee-002');
    expect(text).toContain('1 scenario(s) were inconclusive');
  });

  it('pluralizes multiple mismatches and lists each one', () => {
    const first = feeCase({ caseId: 'CHR-FEE-001', legacyFee: 1.5 });
    const second = feeCase({ caseId: 'CHR-FEE-002', legacyFee: LEGACY_FEE });
    const suite = suiteOf({
      cases: [first.item, second.item],
      captures: [first.baseline, second.baseline],
    });
    const result = compareSuite({
      suite,
      modernExecutions: [
        { caseId: 'CHR-FEE-001', execution: feeModern(1.4) },
        { caseId: 'CHR-FEE-002', execution: feeModern(2) },
      ],
    });
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: result.comparisons,
      mismatches: result.mismatches,
      now: () => FIXED_NOW,
    });
    const text = describeDifferentialReport(report);

    expect(text.split('\n')[0]).toBe('0/2 scenarios equivalent, 2 mismatches');
    expect(text.match(/MISMATCH:/g)).toHaveLength(2);
    expect(text).toContain('legacy 1.5 vs modern 1.4');
    expect(text).toContain('legacy 2.01 vs modern 2');
  });

  it('mentions unreachable scenarios when one side never answered', () => {
    const unreachable = execution(
      'modern',
      [outcome('transfer', { status: 'unreachable', error: 'connect ECONNREFUSED 127.0.0.1:8090' })],
      { status: 'unreachable', error: 'connect ECONNREFUSED 127.0.0.1:8090' },
    );
    const item = feeCase({ caseId: 'CHR-FEE-001', legacyFee: LEGACY_FEE });
    const suite = suiteOf({ cases: [item.item], captures: [item.baseline] });
    const result = compareSuite({
      suite,
      modernExecutions: [{ caseId: 'CHR-FEE-001', execution: unreachable }],
    });
    const report = buildDifferentialReport({
      runId: RUN_ID,
      comparisons: result.comparisons,
      mismatches: result.mismatches,
      now: () => FIXED_NOW,
    });
    const text = describeDifferentialReport(report);

    expect(text).toContain('1 scenario(s) could not be reached on one side');
    expect(report.statistics.unreachable).toBe(1);
    expect(report.statistics.equal).toBe(0);
  });
});
