server.port=8080
spring.application.name=corebank-legacy

spring.datasource.url=jdbc:postgresql://localhost:5432/legacy_bank
spring.datasource.username=legacy
spring.datasource.password=legacy
spring.datasource.hikari.maximum-pool-size=8

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.com.fnb.corebank=INFO
logging.level.org.hibernate=WARN
